name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          version: 1.6.43
          to: html
          path: index.qmd
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          single-commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
